{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "606ffc4f-ce9f-4846-9dfa-0aad69244c3d",
   "metadata": {},
   "source": [
    "# Run Django server"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "8aca5f23-c6df-48af-bba4-5cd33e33f5d5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj'"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d825914-c6f2-4d3b-8ace-11a8ea32a1eb",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ebe2d23f-ce58-41eb-9839-fb112049eb16",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj\n"
     ]
    }
   ],
   "source": [
    "%cd monproj"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7010d4b4-331b-4bd9-8f2b-928e5e8f5536",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj'"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9272afd1-99d8-4e59-b434-98337e67f455",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:00:04\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[22/Jun/2022 16:00:26] \u001b[m\"GET /hello/ HTTP/1.1\" 200 16\u001b[0m\n",
      "[22/Jun/2022 16:00:52] \u001b[m\"GET /hello/ HTTP/1.1\" 200 16\u001b[0m\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:13:36\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:14:49\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[22/Jun/2022 16:15:16] \u001b[m\"GET /hello/?nom=Julie HTTP/1.1\" 200 12\u001b[0m\n",
      "[22/Jun/2022 16:15:39] \u001b[m\"GET /hello/ HTTP/1.1\" 200 16\u001b[0m\n",
      "[22/Jun/2022 16:15:57] \u001b[m\"GET /hello/?ajalkj=laksjlakjs HTTP/1.1\" 200 16\u001b[0m\n",
      "Performing system checks...\n",
      "\n",
      "Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10dc902f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/autoreload.py\", line 228, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/commands/runserver.py\", line 124, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 359, in check\n",
      "    include_deployment_checks=include_deployment_checks,\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 346, in _run_checks\n",
      "    return checks.run_checks(**kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n",
      "    new_errors = check(app_configs=app_configs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 16, in check_url_config\n",
      "    return check_resolver(resolver)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 26, in check_resolver\n",
      "    return check_method()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 256, in check\n",
      "    for pattern in self.url_patterns:\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 407, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj/monproj/urls.py\", line 19, in <module>\n",
      "    from monsite.views import hello\n",
      "  File \"/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj/monsite/views.py\", line 16\n",
      "    def homepage(request):\n",
      "                         ^\n",
      "SyntaxError: unexpected EOF while parsing\n",
      "Performing system checks...\n",
      "\n",
      "Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10ef072f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/autoreload.py\", line 228, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/commands/runserver.py\", line 124, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 359, in check\n",
      "    include_deployment_checks=include_deployment_checks,\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 346, in _run_checks\n",
      "    return checks.run_checks(**kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n",
      "    new_errors = check(app_configs=app_configs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 16, in check_url_config\n",
      "    return check_resolver(resolver)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 26, in check_resolver\n",
      "    return check_method()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 256, in check\n",
      "    for pattern in self.url_patterns:\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 407, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj/monproj/urls.py\", line 19, in <module>\n",
      "    from monsite.views import hello\n",
      "  File \"/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj/monsite/views.py\", line 23\n",
      "    \"pitch\": \"Ma compagnie fait de l'apprentissage ma\n",
      "                                                    ^\n",
      "SyntaxError: EOL while scanning string literal\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:27:11\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:28:51\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:29:12\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[22/Jun/2022 16:29:26] \u001b[m\"GET / HTTP/1.1\" 200 559\u001b[0m\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:30:50\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "\u001b[31m\n",
      "You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\u001b[0m\n",
      "\u001b[31mRun 'python manage.py migrate' to apply them.\n",
      "\u001b[0m\n",
      "June 22, 2022 - 16:56:02\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:02:27\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[22/Jun/2022 17:02:28] \u001b[32m\"GET /admin HTTP/1.1\" 301 0\u001b[0m\n",
      "[22/Jun/2022 17:02:29] \u001b[32m\"GET /admin/ HTTP/1.1\" 302 0\u001b[0m\n",
      "[22/Jun/2022 17:02:29] \u001b[m\"GET /admin/login/?next=/admin/ HTTP/1.1\" 200 1650\u001b[0m\n",
      "[22/Jun/2022 17:02:29] \u001b[m\"GET /static/admin/css/login.css HTTP/1.1\" 200 1203\u001b[0m\n",
      "[22/Jun/2022 17:02:29] \u001b[m\"GET /static/admin/css/base.css HTTP/1.1\" 200 16066\u001b[0m\n",
      "[22/Jun/2022 17:02:30] \u001b[m\"GET /static/admin/css/fonts.css HTTP/1.1\" 200 423\u001b[0m\n",
      "[22/Jun/2022 17:02:30] \u001b[m\"GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1\" 200 80304\u001b[0m\n",
      "[22/Jun/2022 17:02:30] \u001b[m\"GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1\" 200 81348\u001b[0m\n",
      "[22/Jun/2022 17:02:40] \u001b[32m\"POST /admin/login/?next=/admin/ HTTP/1.1\" 302 0\u001b[0m\n",
      "[22/Jun/2022 17:02:40] \u001b[m\"GET /admin/ HTTP/1.1\" 200 3418\u001b[0m\n",
      "[22/Jun/2022 17:02:40] \u001b[m\"GET /static/admin/css/dashboard.css HTTP/1.1\" 200 412\u001b[0m\n",
      "[22/Jun/2022 17:02:41] \u001b[m\"GET /static/admin/img/icon-changelink.svg HTTP/1.1\" 200 380\u001b[0m\n",
      "[22/Jun/2022 17:02:41] \u001b[m\"GET /static/admin/img/icon-addlink.svg HTTP/1.1\" 200 331\u001b[0m\n",
      "[22/Jun/2022 17:02:41] \u001b[m\"GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1\" 200 82564\u001b[0m\n",
      "[22/Jun/2022 17:03:01] \u001b[m\"GET /admin/monsite/book/ HTTP/1.1\" 200 3030\u001b[0m\n",
      "[22/Jun/2022 17:03:02] \u001b[m\"GET /static/admin/css/changelists.css HTTP/1.1\" 200 6170\u001b[0m\n",
      "[22/Jun/2022 17:03:02] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "[22/Jun/2022 17:03:02] \u001b[m\"GET /static/admin/img/tooltag-add.svg HTTP/1.1\" 200 331\u001b[0m\n",
      "[22/Jun/2022 17:03:14] \u001b[m\"GET /admin/monsite/book/add/ HTTP/1.1\" 200 4786\u001b[0m\n",
      "[22/Jun/2022 17:03:14] \u001b[m\"GET /static/admin/css/forms.css HTTP/1.1\" 200 8173\u001b[0m\n",
      "[22/Jun/2022 17:03:14] \u001b[m\"GET /static/admin/js/change_form.js HTTP/1.1\" 200 712\u001b[0m\n",
      "[22/Jun/2022 17:03:14] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "[22/Jun/2022 17:03:14] \u001b[m\"GET /static/admin/js/prepopulate_init.js HTTP/1.1\" 200 495\u001b[0m\n",
      "[22/Jun/2022 17:03:15] \u001b[m\"GET /static/admin/css/widgets.css HTTP/1.1\" 200 10340\u001b[0m\n",
      "Not Found: /favicon.ico\n",
      "[22/Jun/2022 17:03:15] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2173\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 138, in run\n",
      "    self.finish_response()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 180, in finish_response\n",
      "    self.write(data)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 274, in write\n",
      "    self.send_headers()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 332, in send_headers\n",
      "    self.send_preamble()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 255, in send_preamble\n",
      "    ('Date: %s\\r\\n' % format_date_time(time.time())).encode('iso-8859-1')\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 453, in _write\n",
      "    result = self.stdout.write(data)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py\", line 803, in write\n",
      "    self._sock.sendall(b)\n",
      "OSError: [Errno 41] Protocol wrong type for socket\n",
      "[22/Jun/2022 17:03:15] \u001b[35;1m\"GET /favicon.ico HTTP/1.1\" 500 59\u001b[0m\n",
      "----------------------------------------\n",
      "Exception happened during processing of request from ('127.0.0.1', 55113)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 138, in run\n",
      "    self.finish_response()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 180, in finish_response\n",
      "    self.write(data)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 274, in write\n",
      "    self.send_headers()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 332, in send_headers\n",
      "    self.send_preamble()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 255, in send_preamble\n",
      "    ('Date: %s\\r\\n' % format_date_time(time.time())).encode('iso-8859-1')\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 453, in _write\n",
      "    result = self.stdout.write(data)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py\", line 803, in write\n",
      "    self._sock.sendall(b)\n",
      "OSError: [Errno 41] Protocol wrong type for socket\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 141, in run\n",
      "    self.handle_error()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/servers/basehttp.py\", line 88, in handle_error\n",
      "    super(ServerHandler, self).handle_error()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 368, in handle_error\n",
      "    self.finish_response()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 180, in finish_response\n",
      "    self.write(data)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 274, in write\n",
      "    self.send_headers()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 331, in send_headers\n",
      "    if not self.origin_server or self.client_is_modern():\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 344, in client_is_modern\n",
      "    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'\n",
      "TypeError: 'NoneType' object is not subscriptable\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py\", line 654, in process_request_thread\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py\", line 364, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py\", line 724, in __init__\n",
      "    self.handle()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/servers/basehttp.py\", line 155, in handle\n",
      "    handler.run(self.server.get_app())\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/handlers.py\", line 144, in run\n",
      "    self.close()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/wsgiref/simple_server.py\", line 35, in close\n",
      "    self.status.split(' ',1)[0], self.bytes_sent\n",
      "AttributeError: 'NoneType' object has no attribute 'split'\n",
      "----------------------------------------\n",
      "[22/Jun/2022 17:03:58] \u001b[32m\"POST /admin/monsite/book/add/ HTTP/1.1\" 302 0\u001b[0m\n",
      "[22/Jun/2022 17:03:59] \u001b[m\"GET /admin/monsite/book/ HTTP/1.1\" 200 4343\u001b[0m\n",
      "[22/Jun/2022 17:03:59] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "[22/Jun/2022 17:04:00] \u001b[m\"GET /static/admin/img/icon-yes.svg HTTP/1.1\" 200 436\u001b[0m\n",
      "[22/Jun/2022 17:04:04] \u001b[m\"GET /admin/monsite/book/1/change/ HTTP/1.1\" 200 5371\u001b[0m\n",
      "[22/Jun/2022 17:04:05] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "[22/Jun/2022 17:04:10] \u001b[m\"GET /admin/monsite/book/ HTTP/1.1\" 200 4161\u001b[0m\n",
      "[22/Jun/2022 17:04:13] \u001b[m\"GET /admin/monsite/book/add/ HTTP/1.1\" 200 4786\u001b[0m\n",
      "[22/Jun/2022 17:04:13] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "Not Found: /favicon.ico\n",
      "[22/Jun/2022 17:04:15] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2173\u001b[0m\n",
      "[22/Jun/2022 17:04:24] \u001b[32m\"POST /admin/monsite/book/add/ HTTP/1.1\" 302 0\u001b[0m\n",
      "[22/Jun/2022 17:04:25] \u001b[m\"GET /admin/monsite/book/ HTTP/1.1\" 200 4569\u001b[0m\n",
      "[22/Jun/2022 17:04:25] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "[22/Jun/2022 17:04:34] \u001b[m\"GET /admin/monsite/book/add/ HTTP/1.1\" 200 4786\u001b[0m\n",
      "[22/Jun/2022 17:04:35] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "Not Found: /favicon.ico\n",
      "[22/Jun/2022 17:04:37] \u001b[33m\"GET /favicon.ico HTTP/1.1\" 404 2173\u001b[0m\n",
      "[22/Jun/2022 17:04:48] \u001b[32m\"POST /admin/monsite/book/add/ HTTP/1.1\" 302 0\u001b[0m\n",
      "[22/Jun/2022 17:04:48] \u001b[m\"GET /admin/monsite/book/ HTTP/1.1\" 200 4794\u001b[0m\n",
      "[22/Jun/2022 17:04:49] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "[22/Jun/2022 17:16:13] \u001b[m\"GET /admin/ HTTP/1.1\" 200 4312\u001b[0m\n",
      "[22/Jun/2022 17:16:18] \u001b[m\"GET /admin/monsite/book/ HTTP/1.1\" 200 4612\u001b[0m\n",
      "[22/Jun/2022 17:16:19] \u001b[m\"GET /admin/jsi18n/ HTTP/1.1\" 200 3189\u001b[0m\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:21:08\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:21:46\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:21:59\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[22/Jun/2022 17:22:44] \u001b[m\"GET /books/ HTTP/1.1\" 200 945\u001b[0m\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:25:08\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10fbbd620>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/autoreload.py\", line 228, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/commands/runserver.py\", line 124, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 359, in check\n",
      "    include_deployment_checks=include_deployment_checks,\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 346, in _run_checks\n",
      "    return checks.run_checks(**kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n",
      "    new_errors = check(app_configs=app_configs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 16, in check_url_config\n",
      "    return check_resolver(resolver)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 26, in check_resolver\n",
      "    return check_method()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 256, in check\n",
      "    for pattern in self.url_patterns:\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 407, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj/monproj/urls.py\", line 21, in <module>\n",
      "    from monsite.views import books\n",
      "ImportError: cannot import name 'books'\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:37:28\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:37:36\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "Performing system checks...\n",
      "\n",
      "Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1056e5620>\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/autoreload.py\", line 228, in wrapper\n",
      "    fn(*args, **kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/commands/runserver.py\", line 124, in inner_run\n",
      "    self.check(display_num_errors=True)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 359, in check\n",
      "    include_deployment_checks=include_deployment_checks,\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/management/base.py\", line 346, in _run_checks\n",
      "    return checks.run_checks(**kwargs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n",
      "    new_errors = check(app_configs=app_configs)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 16, in check_url_config\n",
      "    return check_resolver(resolver)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/core/checks/urls.py\", line 26, in check_resolver\n",
      "    return check_method()\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 256, in check\n",
      "    for pattern in self.url_patterns:\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 407, in url_patterns\n",
      "    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/utils/functional.py\", line 35, in __get__\n",
      "    res = instance.__dict__[self.name] = self.func(instance)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module\n",
      "    return import_module(self.urlconf_name)\n",
      "  File \"/Users/ivan/.pyenv/versions/3.6.9/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/ivan/Projects/Minireference/software/ateliers-prog/DjangoTutorialFR/monproj/monproj/urls.py\", line 21, in <module>\n",
      "    from monsite.views import books\n",
      "ImportError: cannot import name 'books'\n",
      "Performing system checks...\n",
      "\n",
      "System check identified no issues (0 silenced).\n",
      "June 22, 2022 - 17:38:17\n",
      "Django version 1.11.23, using settings 'monproj.settings'\n",
      "Starting development server at http://127.0.0.1:8000/\n",
      "Quit the server with CONTROL-C.\n",
      "[22/Jun/2022 17:44:51] \u001b[m\"GET /books/ HTTP/1.1\" 200 1574\u001b[0m\n",
      "[22/Jun/2022 17:45:11] \u001b[m\"GET /books/ HTTP/1.1\" 200 1586\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!./manage.py runserver"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d4c5cd5-045a-4f9b-82d5-3cf16a0a53d6",
   "metadata": {},
   "source": [
    "hello \n",
    "```html\n",
    "<!doctype html>\n",
    "<html lang=\"en\">\n",
    "\n",
    "  <head>\n",
    "    <meta charset=\"utf-8\">\n",
    "    <title>Titre de la page</title>\n",
    "    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css\">\n",
    "    <style>\n",
    "        body {\n",
    "          padding-top: 4rem;\n",
    "        }\n",
    "    </style>\n",
    "  </head>\n",
    "\n",
    "  <body>\n",
    "    <main class=\"container\">\n",
    "\n",
    "      <div>\n",
    "        <h1>Titre principal</h1>\n",
    "        <p class=\"lead\">\n",
    "            Texte qui explique l'idée de ton site en deux phrases.<br>\n",
    "            Ceci est un document HTML barebones que nous allons modifier.\n",
    "        </p>\n",
    "      </div>\n",
    "\n",
    "    </main>\n",
    "  </body>\n",
    "\n",
    "</html>\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "56f2c52a-f6ff-4d88-ae0b-3b9fb86b321a",
   "metadata": {},
   "outputs": [],
   "source": [
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d0ab388f-dfa2-45cb-ac8d-daddc6c96518",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36;1mMigrations for 'monsite':\u001b[0m\n",
      "  \u001b[1mmonsite/migrations/0001_initial.py\u001b[0m\n",
      "    - Create model Book\n"
     ]
    }
   ],
   "source": [
    "!./manage.py makemigrations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "2f5430b7-24db-4562-a163-5f7395ac5edd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36;1mOperations to perform:\u001b[0m\n",
      "\u001b[1m  Apply all migrations: \u001b[0madmin, auth, contenttypes, monsite, sessions\n",
      "\u001b[36;1mRunning migrations:\u001b[0m\n",
      "  Applying contenttypes.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying admin.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying admin.0002_logentry_remove_auto_add...\u001b[32;1m OK\u001b[0m\n",
      "  Applying contenttypes.0002_remove_content_type_name...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0002_alter_permission_name_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0003_alter_user_email_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0004_alter_user_username_opts...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0005_alter_user_last_login_null...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0006_require_contenttypes_0002...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0007_alter_validators_add_error_messages...\u001b[32;1m OK\u001b[0m\n",
      "  Applying auth.0008_alter_user_username_max_length...\u001b[32;1m OK\u001b[0m\n",
      "  Applying monsite.0001_initial...\u001b[32;1m OK\u001b[0m\n",
      "  Applying sessions.0001_initial...\u001b[32;1m OK\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!./manage.py migrate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "2f1a9b61-55a7-443b-8676-49354d7a0bb2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Type 'manage.py help <subcommand>' for help on a specific subcommand.\n",
      "\n",
      "Available subcommands:\n",
      "\n",
      "\u001b[31m[auth]\u001b[0m\n",
      "    changepassword\n",
      "    createsuperuser\n",
      "\n",
      "\u001b[31m[contenttypes]\u001b[0m\n",
      "    remove_stale_contenttypes\n",
      "\n",
      "\u001b[31m[django]\u001b[0m\n",
      "    check\n",
      "    compilemessages\n",
      "    createcachetable\n",
      "    dbshell\n",
      "    diffsettings\n",
      "    dumpdata\n",
      "    flush\n",
      "    inspectdb\n",
      "    loaddata\n",
      "    makemessages\n",
      "    makemigrations\n",
      "    migrate\n",
      "    sendtestemail\n",
      "    shell\n",
      "    showmigrations\n",
      "    sqlflush\n",
      "    sqlmigrate\n",
      "    sqlsequencereset\n",
      "    squashmigrations\n",
      "    startapp\n",
      "    startproject\n",
      "    test\n",
      "    testserver\n",
      "\n",
      "\u001b[31m[sessions]\u001b[0m\n",
      "    clearsessions\n",
      "\n",
      "\u001b[31m[staticfiles]\u001b[0m\n",
      "    collectstatic\n",
      "    findstatic\n",
      "    runserver\n"
     ]
    }
   ],
   "source": [
    "!./manage.py help"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c1daffd0-6a35-49f3-a620-ced18046c6a5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee133681-d59d-40b3-bf47-cbc972d78857",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84e6a3f5-b7fe-42de-9b84-902e1a49005e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1796e987-49c6-4c66-aa07-22d17cd6708d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Username (leave blank to use 'ivan'): ^C\n",
      "\n",
      "Operation cancelled.\n"
     ]
    }
   ],
   "source": [
    "!./manage.py createsuperuserah"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "74112b21-3dd8-40bb-8cad-b2af72944ce1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d930682a-94cd-405a-b414-6f91b99a4e0a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "21837909-cb6b-47b5-916b-ecfbb8e03101",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc2448d2-99bb-4cf5-9fd3-a8d6d6c6f6f9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
